apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /user-service(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service: 
              name: otus-health
              port: 
                number: 8080
        - path: /auth-service(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: auth-service
              port:
                number: 8080
        - path: /comm-gate(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: comm-gate
              port:
                number: 8080
        - path: /orders-core(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: orders-core
              port:
                number: 8080

