apiVersion: v1
kind: ConfigMap
metadata:
  name: prometeus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval:     5s # By default, scrape targets every 15 seconds.
      external_labels:
        monitor: 'codelab-monitor'
    scrape_configs:
      - job_name: 'otus-health'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['otus-health:8080']
      - job_name: 'auth-service'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:8080']
      - job_name: 'ingress'
        scrape_interval: 5s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['nginx-ingress-nginx-controller-metrics.m.svc.cluster.local:10254']
      - job_name: 'comm-gate-service'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['comm-gate:8080']
      - job_name: 'document-genarator-service'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['document-generator:8080']
      - job_name: 'orders-core-service'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['orders-core:8080']
      - job_name: 'saga-core-service'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['saga-core:8080']
      - job_name: 'scoring-service'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['scoring:8080']

