apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
#  spring.datasource.username: cG9zdGdyZXM=
#  spring.datasource.password: cGdwYXNz
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cGdwYXNz

