apiVersion: v1
kind: Service
metadata:
  name: otus-health
spec:
  selector:
    app: otus-health
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
  type: NodePort

